version: '3'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    command: start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://database:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=pgsql
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgsql
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d keycloak -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 10